name: Actividad - 4 | Release NuGet Package
env:
  DOTNET_VERSION: '8.0' # la versi√≥n de .NET
on: push


jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
        
      - name: Restore dependencies && Build solution
        run: |
          cd Bank
          dotnet restore
          dotnet build --configuration Release

      - name: Pack NuGet package
        run: |
          dotnet pack Bank/Bank.Domain/Bank.Domain.csproj -c Release \
            -p:PackageVersion=202.207.3503 \
            -p:RepositoryUrl=https://github.com/${{ github.repository }} \
            -p:RepositoryType=git
      - name: NuGet sources
        run: dotnet nuget list source
      - name: Push NuGet package to GitHub Packages
        run: dotnet nuget push Bank/Bank.Domain/bin/Release/*.nupkg --skip-duplicate --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" --api-key ${{ secrets.PACKAGE_NUGET }}
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v2022073503
          name: Release v2022073503
          files: "**/*.nupkg"